---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "../../base/keycloak/20-keycloak"
  - "./httproute.yaml"
  - "./opencenter-realm.yaml"
  - "./rbac-manager-users.yaml"
patchesStrategicMerge:
  - "./keycloak-cr-patch.yaml"
