apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: rbac-manager-users
rbacBindings:
  - name: k8s-admins
    subjects:
      - kind: Group
        name: "oidc:k8s-admins"
    clusterRoleBindings:
      - clusterRole: cluster-admin
  - name: k8s-viewers
    subjects:
      - kind: Group
        name: "oidc:k8s-viewers"
    clusterRoleBindings:
      - clusterRole: view
  - name: k8s-auditor
    subjects:
      - kind: Group
        name: "oidc:k8s-auditor"
    clusterRoleBindings:
      - clusterRole: view
  - name: k8s-ops
    subjects:
      - kind: Group
        name: "oidc:k8s-ops"
    clusterRoleBindings:
      - clusterRole: k8s-ops
  - name: k8s-developers-app1
    subjects:
      - kind: Group
        name: "oidc:k8s-developers-app1"
    roleBindings:
      - clusterRole: edit
        namespace: app1
  - name: k8s-viewers-app1
    subjects:
      - kind: Group
        name: "oidc:k8s-developers-app1"
    roleBindings:
      - clusterRole: view
        namespace: app1
