---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: prometheus-oidc
  namespace: observability
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: prometheus-gateway-route
  oidc:
    provider:
      issuer: "https://auth.oc-poc2.td2.k8s.rmpk.dev/realms/opencenter"
    clientID: "opencenter"  
    clientSecret:
      name: "gateway-oidc-secret" 
    redirectURL: "https://prometheus.oc-poc2.td2.k8s.rmpk.dev/oauth2/callback"
    scopes:
      - openid
      - profile
      - email
      - roles
    logoutPath: "/logout"
