---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux-system
  - ./services/fluxcd
{{- range $name, $service := .OpenCenter.ManagedServices }}
  {{- if $service.Enabled }}
  - ./managed-services/fluxcd
  {{- break }}
  {{- end }}
{{- end }}
{{- if .OpenCenter.GitOps.OverlayUnits.CustomerManaged.Enabled }}
  - ./customer-managed/fluxcd
{{- end }}
