adminUser:
    create: ENC[AES256_GCM,data:UNdo+w==,iv:+DHQdJQuELEclt+z0hQe3CnXs9D2aqBYRJO8u+YiuOI=,tag:BHelMF9SUOy9ZXJQMDexQA==,type:bool]
    username: ENC[AES256_GCM,data:FdQoIk4=,iv:Z/Ma4PlgVyJVeVIGKm/mw5MDoEODBQ3O/DJeD0xYXsA=,tag:7JSmW+q4GQjpZOyZvxQiCQ==,type:str]
    passwordHash: ENC[AES256_GCM,data:O5SMP8Iuuwvc+uo5oaELlzn/ovVYnEDJjIxhySkbqtxAB3t62dTNfjc3nr/m25zsgKThyUOi84FGUEL9,iv:if7eHsojyUrlQ4+kvtFMP0K2eeFx17IXRjxRtnKK3GM=,tag:78KxWTCK64jFY0pLGrz4tg==,type:str]
sops:
    age:
        - recipient: age1ydr20ml7gdda4pkq5exe4amr426xtxnkwl2sdtt2zlxnu2jhg90qe2u4qk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQjdpYTcyaSt1akJldGZs
            eDdHd3B6VFpUYWxobXFoeHp0N0pqUlhCejJZCmFydlYweU1wR2VBVkwyQjM5Mkg0
            dU5LKzhCZjNHZzQrK3d1OGFlekVuM28KLS0tIFhoTzJqdEloOHVvSjh1QWFiclha
            ckg5NThWM2t5Tm1jRVVhaDduOTlvWnMKDkelZ3Ml4737wnj9yqdG1Oz3ZO0VI7BO
            2yXY2kVFGaD/q82OZYRo2JsqF95MvFUoiN2GkOvOQGNRhG26uBKkxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-17T18:40:06Z"
    mac: ENC[AES256_GCM,data:U4YjTIryqmEoNOz2b9qo+9I8FpnRB4N9cIXDe6hhxksSc5qDfS1BAOwwwXcDjIEPVS/UVM4XL59ib3q8XI2AIDDXTdXVq9NTIm1rLmNd9tXwp6DOltnHQF+SfJA8zwEuiPCEyBUxP6f13jur6edQZFXhTc8YWCm4f/WAAM8KU7E=,iv:7K4RrDFdDb/bOq7bnHnHEpcIk7BYgjJhQRLxYmlLIoA=,tag:DmZBOJ4iUj42jch8buXWGQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
