---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sources.yaml
  - ./gateway-api.yaml
  - ./cert-manager.yaml
  - ./olm.yaml
  - ./gateway.yaml
  - ./velero.yaml
  - ./kube-prometheus-stack.yaml
  - ./openstack-ccm.yaml
  - ./openstack-csi.yaml
  - ./weave-gitops.yaml
  - ./external-snapshotter.yaml
  - ./rbac-manager.yaml
