apiVersion: v1
kind: Secret
metadata:
    name: alert-manager-base-url-secret
type: generic
stringData:
    alert_manager_base_url:
        {
            {
                (index .OpenCenter.ManagedServices "alert-proxy").AlertManagerBaseUrl,
            },
        }
