apiVersion: v1
kind: Secret
metadata:
    name: http-route-fqdn-secret
    namespace: rackspace
type: Opaque
data:
    http_route_fqdn:
        {
            {
                (index .OpenCenter.ManagedServices "alert-proxy").AccountServiceToken,
            },
        }
