secret:
    enabled: true
    hostMount: true
    create: true
    filename: cloud.conf
    name: cinder-csi-cloud-config
    data:
        cloud.conf: |-
            [Global]
            auth-url = https://keystone.td2.rpc.rackspace.com/v3
            application-credential-id = 00ca08150cc24be8a3ea014f44763aee
            application-credential-secret = O38T5b2vQ6SJt89_ZHEHtfAEL4sX8XHvvOeP1HSRG7kvs0QgskGvvakzaxtiSvMSsiovSfQhnrsmqgdi_z_QOg
            domain-name = Default
            region = RegionOne
            tenant-name = oc-poc2
            tls-insecure =  false
