// Copyright 2025 Victor Palma <victor.palma@rackspace.com>
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package stages

import (
	"context"
	"fmt"
	"os"

	"github.com/rackerlabs/openCenter-cli/internal/config"
	"github.com/rackerlabs/openCenter-cli/internal/gitops"
)

// InitStage creates the base directory structure for the GitOps repository.
// This is typically the first stage in the generation pipeline.
type InitStage struct {
	BaseStage
}

// NewInitStage creates a new initialization stage.
func NewInitStage() *InitStage {
	return &InitStage{
		BaseStage: NewBaseStage(
			"init",
			"Initialize base directory structure",
			[]string{}, // No dependencies
		),
	}
}

// Execute creates the base directory structure.
func (is *InitStage) Execute(ctx context.Context, workspace *gitops.GitOpsWorkspace) error {
	// Create base directories
	directories := []string{
		"infrastructure",
		"infrastructure/clusters",
		"applications",
		"applications/base",
		"applications/overlays",
		".flux-system",
	}

	writer := gitops.NewAtomicWriter(workspace)
	writer.SetStage(is.Name()) // Set stage name for dry-run tracking

	for _, dir := range directories {
		if err := writer.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("failed to create directory %s: %w", dir, err)
		}
	}

	// Create a README file
	readmeContent := fmt.Sprintf(`# GitOps Repository for %s

This repository contains the GitOps configuration for the %s cluster.

## Structure

- **infrastructure/**: Infrastructure-level configurations
- **applications/**: Application manifests and configurations
- **.flux-system/**: Flux CD system configurations

Generated by openCenter CLI
`, workspace.Config.ClusterName(), workspace.Config.ClusterName())

	if err := writer.WriteFileString("README.md", readmeContent, 0o644); err != nil {
		return fmt.Errorf("failed to create README: %w", err)
	}

	// Create .gitignore
	gitignoreContent := `# Temporary files
*.tmp
*.swp
*~

# Secrets (should be encrypted with SOPS)
secrets/*.yaml
!secrets/*.enc.yaml

# Local development
.env
.env.local
`

	if err := writer.WriteFileString(".gitignore", gitignoreContent, 0o644); err != nil {
		return fmt.Errorf("failed to create .gitignore: %w", err)
	}

	return nil
}

// Rollback removes the directories created by this stage.
func (is *InitStage) Rollback(ctx context.Context, workspace *gitops.GitOpsWorkspace) error {
	// Remove all files and directories created by this stage
	paths := []string{
		"README.md",
		".gitignore",
		"infrastructure",
		"applications",
		".flux-system",
	}

	for _, path := range paths {
		fullPath := workspace.GetPath(path)
		if err := os.RemoveAll(fullPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("failed to remove %s during rollback: %w", path, err)
		}
	}

	return nil
}

// Validate checks that the base structure was created correctly.
func (is *InitStage) Validate(ctx context.Context, workspace *gitops.GitOpsWorkspace) error {
	// Check that required directories exist
	requiredDirs := []string{
		"infrastructure",
		"infrastructure/clusters",
		"applications",
		"applications/base",
		"applications/overlays",
		".flux-system",
	}

	for _, dir := range requiredDirs {
		if !workspace.Exists(dir) {
			return fmt.Errorf("required directory not found: %s", dir)
		}
	}

	// Check that required files exist
	requiredFiles := []string{
		"README.md",
		".gitignore",
	}

	for _, file := range requiredFiles {
		if !workspace.Exists(file) {
			return fmt.Errorf("required file not found: %s", file)
		}
	}

	return nil
}

// DryRun returns a plan of what this stage would create.
func (is *InitStage) DryRun(ctx context.Context, cfg config.Config) (*gitops.StagePlan, error) {
	return &gitops.StagePlan{
		Name:        is.Name(),
		Description: is.Description(),
		Files: []string{
			"README.md",
			".gitignore",
		},
		Directories: []string{
			"infrastructure",
			"infrastructure/clusters",
			"applications",
			"applications/base",
			"applications/overlays",
			".flux-system",
		},
		Dependencies: is.Dependencies(),
	}, nil
}
