apiVersion: v1
kind: Secret
metadata:
  name: velero-credentials
  namespace: velero
type: Opaque
stringData:
  OS_AUTH_URL: ENC[AES256_GCM,data:9dFioQ4SFssBOXISlhJz29BR8HLJgXyCjk/3A9P49kwMcuDCK5KczPZQC7+TfJs=,iv:kpt8qDqruetOvTJJ3ke/mZU7CKG/ldqyxWGJVXks8oY=,tag:dg/3TaUlOSFjWpRPHdMMgA==,type:str]
  OS_PROJECT_NAME: ENC[AES256_GCM,data:/O73t1SMiEDiTOMlDLJmaspP/Dn3zd2fZRwoX+EAKpqSztuy,iv:AnNABnJE254X4uzEopAleFfT/dG6yMLaWAXpdOerfqo=,tag:uG2Yq+vx8Iw9VbE44M244Q==,type:str]
  OS_APPLICATION_CREDENTIAL_ID: ENC[AES256_GCM,data:l6/YGofK3V76GU7yOw3fp0U74823bqjL42uVBTJMRlU=,iv:lB8uRHnr+AUG+Adok1xogujFVVpbMneRMjv0em4CW8U=,tag:O5pD5sJsumXREmiaELjxcQ==,type:str]
  OS_APPLICATION_CREDENTIAL_SECRET: ENC[AES256_GCM,data:Ss8t6BObmaelyur1Vim/Ro2GrUfXTQ0020Atexf0yYTykAC298bGC5WLv9lwkvL1PnozkZY6OHHiZ0dQKW54cf/FxvA8X8Xie4mfuuQD4FvUX0woFSE=,iv:/YduL2FTrULSllq/lcfX+HcQHVxwCHg2cGmpQ7f9OL8=,tag:+WzPRj/Y0wv1HzDM+7HUgg==,type:str]
  OS_REGION_NAME: ENC[AES256_GCM,data:e/S9+g==,iv:N07BWULONmFrjtqCKFMeTajqQrtyA6pOqZslyIadExM=,tag:OA2MwSsWUkJbpV4GljmWbw==,type:str]
  OS_DOMAIN_NAME: ENC[AES256_GCM,data:8RQQ+alEvcsTMuGczGFNaZlpYL093w==,iv:P/SB6WnwXWrzjTVuM8ewjS1T7h4C3wzzYnm5IAzVStc=,tag:zRypI4GpHW/L6xw0Bavxkg==,type:str]
sops:
  age:
    - recipient: age1ydr20ml7gdda4pkq5exe4amr426xtxnkwl2sdtt2zlxnu2jhg90qe2u4qk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Uk5aK2VTSkZMRWV3MnRq
        Z1JUbHMzZ1JkQ2lpR24xb2ZCc1BLRWFSUXlJCldISlMyZkQ2a0VwQytuSG10Qmh0
        cERoaDFGODQxMExrQzVIMlJEbmUxSXMKLS0tIDMrNGhEYlEwN1BabldSaEkwaExU
        MDRTNm9heUZQQzhZZnNyZys3ZHkvQjAKFk4Q4gp/X8kmiYre63jbFDnmIKPmSUQG
        roN6X+7r8/EVPo2PJcaRsoOlodO458URv7L3hxkF4+IHHtJtKjOkhg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-17T17:05:22Z"
  mac: ENC[AES256_GCM,data:bWfI8HAa2uREEzRrR0PlNYNKoFmrrcltY1kIgBAOYwh1xUt2dzrxEy6W6D+ftkPo3SWB9ntHjb/aF0IpNpgze0teSxvHDOeurwxmnWIrDyQOBUfQn81cx6VcZKHgYfM1TIPNbvDymqhVumgCkWgfJu7fOuSniyO0MYsVHfo9Loo=,iv:07Hfuztbe/tRTgtwXUArL/XZ5hJMdqFEnWirfenXdDo=,tag:T7YQCy9O3s2xdbs06wasew==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
