apiVersion: v1
data:
  access-key-id: ENC[AES256_GCM,data:maeDW1jjdDYcgGH9sEwRQ2ZoB9NrBWhK8M32sQ==,iv:Rn1tFrObxdoGcsViv7RrpLx1UHKwQNk+k77m1Jestf0=,tag:g8d/kmk6ugK+qOIJ4q7zDA==,type:str]
  secret-access-key: ENC[AES256_GCM,data:LtrioPKW+fkFr8TCIRuWPpUl53lnMhqHd2rcNDuD3JhOf2NUxBpdNNnhelzKUKv9oCkYtPkbgvU=,iv:hRiE9oZPMhPujq3RYJkMNqv0NQVdswYOZYVzgyqZHgM=,tag:6UMY6AbMP7DN4WOPzvzbhQ==,type:str]
kind: Secret
metadata:
  name: 1342585-prosys-aws-credentials-secret
sops:
  age:
    - recipient: age1ydr20ml7gdda4pkq5exe4amr426xtxnkwl2sdtt2zlxnu2jhg90qe2u4qk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQUREVTIwNVYyUy9PSFM4
        M0JidVArNzlmOU5oVUhqNzM1VDB3ekNTaG5rCmRTTE9Eb3JnTTN3ajM1MUFFRWg4
        NVB6cjdqR2wzTmVadTJUTGxRMGFOYjgKLS0tIGw5b2JjSUZ5WTk3UHZRK0l0Tkh2
        em1pU0cwcFBGOWoxM2NOdDYwTDF2ZVkKlOkVtD50fxG+fAwQkmhMr9crL89ONC2O
        fE2qnAAVa64OpmYrYroIvKIvWcfyjcodL/OoheOlwQfmoD3noIOQ/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-18T12:05:17Z"
  mac: ENC[AES256_GCM,data:dfNTvAfSqAnZAnGzEMoR7QxFAw0FJhZdtGXAORFmHjxZgFlWq/H0U6sKIn96o9h1TChVxgSjff6xA288ePMIcl5+kCG7Rza0f4pm3mIF8utIhIwZdeGu2yvtIz9TZHgq5tHteb052mpsD2tMoILXP3lJszUepG264fwBYVmaZ1I=,iv:+I+yG//z44izLpE3f+tQQjH+AQ23WXTonn8iU/LxU3w=,tag:9hq0XvGvnIGhRy0LzQh5Ig==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
