apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: alert-proxy
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: alert-proxy
    namespace: flux-system
  chart: ./helm
