---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
secretGenerator:
  - name: tempo-values-override
  type: Opaque
  files: [override.yaml=helm-values/override-values.yaml]
  options:
  disableNameSuffixHash: true
